### ISSUE TITLE
Alternate to time.sleep to identify when the page has loaded the search results.

### ISSUE THREAD

**Issue by mancunian1792** [mancunian1792/Pyt_Scrape_SBB#3]
Since, the results load in the same page, the page id is the same and i can't identify when the search results has been loaded to the dom. Guessing game now with time.sleep

**Comment by aravinthchandramouli** [comment]
put a sleep for 30-45 seconds da. by that time, results should load.

**Comment by mancunian1792** [comment]
Okay, if sleep is okay for you then, i'd have the same approach . I wanted to avoid time.sleep

**Comment by mancunian1792** [comment]
Modified with webdriver wait.
